name: Weekly Summary
on:
  schedule:
    - cron: "0 12 * * 0" # Sundays 12:00 UTC (~8 AM US/Eastern)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Send weekly summary
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        run: |
          python -m scripts.weekly_summary
